version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: saurabh12
      POSTGRES_PASSWORD: saurabh123
    ports:
      - "5433:5432"  # Map container port 5433 to host port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

